# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  domain_name: example.com
  secret_key_base: a32d2155bc6854929b2ae133ab62d62bbece37c9e3c42c356039704b44ffc8ef44ab08373074a3e43faa26ff2c2a9909ff436081fa9f5c0c8d0392c3ba7913dd

test:
  secret_key_base: 51f2d902cb70354945299700926c9be0981b0fe18fcc8619bf31e8fe9bb015dc0a945c4bbad4034abccb9491dbaef8bf33818c7790c25e768c2f0776a9836b19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
